name: Moose Build Workflow

on:
  push:
    branches:
      - main

jobs:
  Build-Moose:
    runs-on: ubuntu-latest
    steps:
      - name: Build informations
        run: |
            echo "Triggered by:  ${{ github.event_name }}"
            echo "Running on:    ${{ runner.os }}"
            echo "Branch name:   ${{ github.ref }}"
            echo "Repository:    ${{ github.repository }}"
            echo "Commit-Id:     ${{ github.sha }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare build output folders
        run: |
          mkdir -p build/Moose_Include_Dynamic
          mkdir -p build/Moose_Include_Static
      - name: Install Lua 5.3
        run: |
          sudo apt-get install lua5.3 liblua5.3-dev
      - name: Check Lua version
        run: |
          lua -v
      - name: Install LuaRocks
        run: |
          sudo apt install luarocks
      - name: Check LuaRocks version
        run: |
          luarocks --version
      - name: Install Lua 5.3 Dev for prerequisites for LuaSrcDiet
        run: |
          sudo apt-get install liblua5.3-dev
      - name: Install LuaSrcDiet
        run: |
          sudo luarocks install luasrcdiet
      - name: Install LuaCheck
        run: |
          sudo luarocks install luacheck
      - name: Build Include Static
        run: |
          lua5.3 "./Moose Setup/Moose_Create.lua" S "${{ github.sha }}" "./Moose Development/Moose" "./Moose Setup" "./build/Moose_Include_Static"
      - name: Build Includes Dynamic
        run: |
          lua5.3 "./Moose Setup/Moose_Create.lua" D "${{ github.sha }}" "./Moose Development/Moose" "./Moose Setup" "./build/Moose_Include_Dynamic"
      - name: Run LuaSrcDiet
        run: |
          luasrcdiet --basic --opt-emptylines ./build/Moose_Include_Static/Moose.lua -o ./build/Moose_Include_Static/Moose_.lua
      - name: Run LuaCheck
        continue-on-error: true
        # run: luacheck --std=lua51c --config=./.luacheckrc -guras ./build/Moose_Include_Static/Moose.lua
        run: |
          luacheck --std=lua51c --config=.luacheckrc -guras "Moose Development/Moose"
      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}/build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            build/**/*.lua
      - run: echo "This job's status is ${{ job.status }}."
