name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Build-Moose:
    runs-on: ubuntu-latest
    steps:
      - name: Build informations
        run: |
            echo "Triggered by:  ${{ github.event_name }}"
            echo "Running on:    ${{ runner.os }}"
            echo "Branch name:   ${{ github.ref }}"
            echo "Repository:    ${{ github.repository }}"
            echo "Commit-Id:     ${{ github.sha }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Lua 5.3
        run: |
          sudo apt-get install lua5.3 liblua5.3-dev
      - name: Check Lua version
        run: |
          lua -v
      - name: Install LuaRocks
        run: |
          sudo apt install luarocks
      - name: Check LuaRocks version
        run: |
          luarocks --version
      - name: Install Lua 5.3 Dev for prerequisites for LuaSrcDiet
        run: |
          sudo apt-get install liblua5.3-dev
      - name: Install LuaSrcDiet
        run: |
          sudo luarocks install luasrcdiet
      - name: Install LuaCheck
        run: |
          sudo luarocks install luacheck
      - name: Build includes
        run: |
          lua5.3 "./Moose Setup/Moose_Create.lua" S "${{ github.sha }}" "./Moose Development/Moose" "./Moose Setup" "./build"
      - name: List files in the repository
        run: |
          ls -l ${{ github.workspace }}/build
      - run: echo "This job's status is ${{ job.status }}."
